version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-north-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...          
      - sleep 1300
      - docker build -t codebuildtest:latest .
      - docker tag codebuildtest 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/codebuildtest:latest      
      - echo "123" > 123.txt
      - echo "123" > /root/abc/cba.txt
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/codebuildtest:latest
      - du -sh /var/log/
artifacts:
  files: 123.txt
cache:
  paths:
    - /var/log/**/*
    - /var/lib/docker/**/*
