version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-north-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuildtest:latest .
      - docker tag codebuildtest 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/codebuildtest:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/codebuildtest:latest
      - mkdir -P /root/test1
      - cp -R /var/log/ /root/test1/
cache:
  paths:
    -'/root/test1/**/*'
