version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-north-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuildtest:latest .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/codebuildtest:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780882641999.dkr.ecr.cn-north-1.amazonaws.com.cn/codebuildtest:latest
